name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js v18.14.2
        uses: actions/setup-node@v3
        with:
          node-version: 18.14.2
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@main
        env:
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          EXCLUDE: '.htaccess'
          SOURCE: "/out"
          TARGET: ${{ secrets.REMOTE_TARGET }}
